import type { Metadata } from "next";
import { Header } from "@/components/organisms/Header";
import { Footer } from "@/components/atoms/Footer";
import { Background } from "@/components/atoms/Background";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function WithNavigationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<Background>
				<Header />
				<main>{children}</main>
			</Background>
			<Footer />
		</>
	);
}
