import type { Metadata } from "next";
import { VStack } from "@/styled-system/jsx";
import { Footer } from "@/components/atoms/Footer";
import { BrandLogoLink } from "@/components/atoms/BrandLogo";
import { Background } from "@/components/atoms/Background";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function WithNavigationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<main>
				<Background>
					<VStack gap="1rem">
						<BrandLogoLink />
						{children}
					</VStack>
				</Background>
			</main>
			<Footer />
		</>
	);
}
