import type { Metadata } from "next";
import { Footer } from "@/components/atoms/Footer";
import { BrandLogoLink } from "@/components/atoms/BrandLogo";
import { vstack } from "@/styled-system/patterns";
import { Background } from "@/components/atoms/Background";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function WithNavigationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<main className={vstack({ alignItems: "stretch" })}>
			<Background>
				<BrandLogoLink />
				{children}
			</Background>
			<Footer />
		</main>
	);
}
