import type { Metadata } from "next";
import { Footer } from "@/components/atoms/Footer";
import { styled } from "@/styled-system/jsx";
import { Title } from "@/components/atoms/Title";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const Background = styled("div", {
	base: {
		backgroundImage: 'url("/bg-lg.webp")',
		backgroundSize: "cover",
		backgroundRepeat: "no-repeat",
		backgroundPosition: "center bottom",
		p: "4",
		minHeight: "100dvh",
	},
});

export default function WithNavigationLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<>
			<Background>
				<Title>Cyberware</Title>
				{children}
			</Background>
			<Footer />
		</>
	);
}
