import "./globals.css";
import type { Metadata } from "next";
import { shareTechMono, sarpanch, orbitron } from "@/app/fonts";
import { Footer } from "@/components/atoms/Footer";
import { Header } from "@/components/organisms/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${shareTechMono.variable} ${sarpanch.variable} ${orbitron.variable}`}
		>
			<body className={shareTechMono.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
